const data = {
    content: [
      {
        id: 4,
        prescriptionDate: "2024-05-25",
        patientName: "Yeamin",
        patientAge: 28,
        patientGender: "MALE",
        diagnosis: "B-Trait",
        medicines: "Paracetamol, Fexo",
        nextVisitDate: "2024-02-06",
      },
      {
        id: 5,
        prescriptionDate: "2024-05-25",
        patientName: "Yeamin",
        patientAge: 28,
        patientGender: "MALE",
        diagnosis: "B-Trait",
        medicines: "Paracetamol, Fexo",
        nextVisitDate: "2024-02-06",
      },
      {
        id: 6,
        prescriptionDate: "2024-05-25",
        patientName: "Yeamin",
        patientAge: 28,
        patientGender: "MALE",
        diagnosis: "B-Trait",
        medicines: "Paracetamol, Fexo",
        nextVisitDate: "2024-02-06",
      },
    ],
    pageable: {
      pageNumber: 0,
      pageSize: 3,
      sort: {
        empty: true,
        sorted: false,
        unsorted: true,
      },
      offset: 0,
      paged: true,
      unpaged: false,
    },
    last: false,
    totalElements: 8,
    totalPages: 3,
    size: 3,
    number: 0,
    sort: {
      empty: true,
      sorted: false,
      unsorted: true,
    },
    first: true,
    numberOfElements: 3,
    empty: false,
  };